smoothie_mixer/config/routes.rb
SmoothieMixer::Application.routes.draw do
  resources :fruits
  resources :bills

  root :to => 'fruits#index'
  match 'search' => 'bills#search'

end

smoothie_mixer/app/models/bill.rb
require 'roar/representer/feature/client'

class Bill
  include Roar::Representer::Feature::HttpVerbs

  extend ActiveModel::Naming
  include ActiveModel::Conversion

  def initialize(*)
    extend Orcharding::BillRepresenter
    extend Roar::Representer::Feature::Client
    transport_engine = Roar::Representer::Transport::Faraday
    @persisted = true if @persisted.nil?
  end
  
  # FIXME: why can't we override #id here?
  def id
    links[:self].href
  end
  
  def url
    links[:self].href
  end

  def to_param
    CGI::escape(url)
  end

  def self.from_param(param)
    find_by_id(param)
  end

  def persisted?
    @persisted
  end
  
  def errors
    []
  end
end

smoothie_mixer/app/models/bills.rb
require 'roar/representer/feature/client'

class Bills < OpenStruct
  include Roar::Representer::Feature::HttpVerbs

  def initialize
    extend Orcharding::BillsRepresenter
    extend Roar::Representer::Feature::Client
    transport_engine = Roar::Representer::Transport::Faraday
  end
end

smoothie_mixer/app/models/fruit.rb
require 'roar/representer/feature/client'

class Fruit
  include Roar::Representer::Feature::HttpVerbs

  extend ActiveModel::Naming
  include ActiveModel::Conversion

  def initialize(*)
    extend Orcharding::FruitRepresenter
    extend Roar::Representer::Feature::Client
    transport_engine = Roar::Representer::Transport::Faraday
    @persisted = true if @persisted.nil?
  end
  
  # FIXME: why can't we override #id here?
  def id
    links[:self].href
  end
  
  def url
    links[:self].href
  end

  def to_param
    CGI::escape(url)
  end

  def self.from_param(param)
    find_by_id(param)
  end

  def persisted?
    @persisted
  end
  
  def errors
    []
  end
end

smoothie_mixer/app/models/fruits.rb
require 'roar/representer/feature/client'

class Fruits < OpenStruct
  include Roar::Representer::Feature::HttpVerbs

  def initialize
    extend Orcharding::FruitsRepresenter
    extend Roar::Representer::Feature::Client
    transport_engine = Roar::Representer::Transport::Faraday
  end
end

smoothie_mixer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

smoothie_mixer/app/controllers/bills_controller.rb
require "book_of_orcharding/representers/bill_representer"
require "book_of_orcharding/representers/bills_representer"

class BillsController < ApplicationController
  include Roar::Rails::ControllerAdditions

  def index
    @bills = Bills.get("http://localhost:9292/bills", 'application/json').bills
  end

  def edit
    @bill = Bill.get(params[:id], 'application/json')
  end

  def search
    puts '<params>'
    puts params
    puts '</params>'
    if params.has_key? 'q'
      @bills = Bills.get("http://localhost:9292/search/#{params[:q]}", 'application/json').bills || []
    else
      @bills = Bills.get("http://localhost:9292/search", 'application/json').bills
    end

  end
end

smoothie_mixer/app/controllers/fruits_controller.rb
require "book_of_orcharding/representers/fruit_representer"
require "book_of_orcharding/representers/fruits_representer"

class FruitsController < ApplicationController
  include Roar::Rails::ControllerAdditions

  def index
    @fruits = Fruits.get("http://localhost:9292/fruits", 'application/json').fruits
  end

  def edit
    @fruit = Fruit.get(params[:id], 'application/json')
  end
end

smoothie_mixer/app/helpers/application_helper.rb
module ApplicationHelper
end

smoothie_mixer/app/helpers/fruit_helper.rb
module FruitHelper
end

smoothie_mixer/app/views/bills/_form.html.haml
= form_for @bill do |f|
  -if @bill.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bill.errors.count, "error")} prohibited this bill from being saved:"
      %ul
        - @bill.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :origin_chamber, :class => 'control-label'
    .controls
      = f.text_field :origin_chamber, :class => 'text_field'
  .actions
    = f.submit 'Save'

smoothie_mixer/app/views/bills/edit.html.haml
- model_class = @bill.class
%h1=t '.title'#, :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

smoothie_mixer/app/views/bills/index.html.haml
%h1=t '.title', :default => 'Bill'
%table.table.table-striped
  %thead
    %tr
      %th= 'Title'
      %th= 'Chamber'
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @bills.each do |bill|
      %tr
        %td= bill.title
        %td= bill.chamber
/         %td
/           = link_to t('.edit', :default => t("helpers.links.edit")), edit_fruit_path(fruit), :class => 'btn btn-mini'
/           = link_to t('.destroy', :default => t("helpers.links.destroy")), fruit_path(fruit), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

/ = link_to t('.new', :default => t("helpers.links.new")), new_fruit_path, :class => 'btn btn-primary'

smoothie_mixer/app/views/bills/search.html.haml
%h1=t '.title', :default => 'Bill'
%table.table.table-striped
  %thead
    %tr
      %th= 'Bulletin'
      %th= 'Title'
      %th= 'Stage'
      %th= 'Creation date'
      %th= 'Publish date'
      / %th= 'Chamber'
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @bills.each do |bill|
      %tr
        %td= bill.uid
        %td= bill.title
        %td= 'Oli'
        %td= bill.creation_date.gsub('T00:00:00+00:00', '')
        %td= 'Otro oli'
        / %td= bill.origin_chamber
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_bill_path(bill), :class => 'btn btn-mini'
= form_tag("/search", :method => "get") do
  = label_tag(:q, "Search for:")
  = text_field_tag(:q)
  = submit_tag("Search")
/           = link_to t('.destroy', :default => t("helpers.links.destroy")), fruit_path(fruit), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

/ = link_to t('.new', :default => t("helpers.links.new")), new_fruit_path, :class => 'btn btn-primary'

smoothie_mixer/app/views/fruits/_form.html.haml
= form_for @fruit do |f|
  -if @fruit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@fruit.errors.count, "error")} prohibited this fruit from being saved:"
      %ul
        - @fruit.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :taste, :class => 'control-label'
    .controls
      = f.text_field :taste, :class => 'text_field'
  .actions
    = f.submit 'Save'

smoothie_mixer/app/views/fruits/edit.html.haml
- model_class = @fruit.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

smoothie_mixer/app/views/fruits/index.html.haml
%h1=t '.title', :default => 'Fruit'
%table.table.table-striped
  %thead
    %tr
      %th= 'Name'
      %th= 'Taste'
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @fruits.each do |fruit|
      %tr
        %td= fruit.name
        %td= fruit.taste
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_fruit_path(fruit), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), fruit_path(fruit), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_fruit_path, :class => 'btn btn-primary'

smoothie_mixer/app/views/fruits/new.html.haml
- model_class = @fruit.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

smoothie_mixer/app/views/fruits/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_fruit_path(@fruit)
\|
= link_to 'Back', fruits_path

smoothie_mixer/app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

smoothie_mixer/app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Cabildo Abierto"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Cabildo Abierto
          .container.nav-collapse
            %ul.nav
              %li= link_to "Home", "/"
              %li= link_to "Fruit", "/fruits"

    .container

      .content
        .row
          .span9
            = render 'layouts/messages'
            = yield
          .span3
            .well.sidebar-nav
              %h3 Sidebar
              %ul.nav.nav-list
                %li.nav-header Sidebar
                %li= link_to "Home", "/"
                %li= link_to "Fruit", "/fruits"
    
      %footer
        %p &copy; Roar client example 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
